name: 打包react项目

on: push

permissions:
  contents: write

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库代码
        uses: actions/checkout@v4
      - name: 安装依赖和项目打包
        run: |
          npm install
          npm run build
      - name: 部署
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: build
